### ISSUE TITLE
相关文档数量判断

### ISSUE THREAD

**Issue by RockChinQ** [michaelliao/llm-embedding-sample#1]
https://github.com/michaelliao/llm-embedding-sample/blob/70f544a0fbac669ecf3cdeeaf35e1203c48da70c/app.py#L136

这里是否应该是 `len(docs) >= 1`，仅搜索到一个文档时也应该判断距离并使用？

**Comment by michaelliao** [comment]
是

**Comment by michaelliao** [comment]
https://github.com/michaelliao/llm-embedding-sample/commit/cac1adade59c5a984863c49c670ca039656baa92
